from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
ITEMS_DIR = ROOT / "items"
AGGREGATE_PATH = ROOT / "library-data" / "items.json"
GENERATED_MARKER = "Generated by scripts/build-library.py"
TEXT_SUFFIXES = {".txt", ".md", ".markdown", ".html", ".htm", ".css", ".js", ".json", ".xml", ".csv", ".py"}
CODE_SUFFIXES = {".html", ".htm", ".css", ".js", ".json", ".xml", ".py", ".sh", ".sql", ".yaml", ".yml"}
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}
VIDEO_SUFFIXES = {".mp4", ".webm", ".mov", ".m4v"}
DOCUMENT_SUFFIXES = {".pdf", ".doc", ".docx", ".ppt", ".pptx", ".xls", ".xlsx"}


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"Missing required file: {path.relative_to(ROOT)}")
    except json.JSONDecodeError as exc:
        fail(f"Invalid JSON in {path.relative_to(ROOT)}: {exc}")


def clean(value) -> str:
    return str(value or "").strip()


def humanize(value: str) -> str:
    return clean(value).replace("-", " ").title()


def web_path(path: Path, base: Path) -> str:
    return "/".join(quote(part) for part in path.relative_to(base).parts)


def list_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(
        (path for path in directory.rglob("*") if path.is_file() and not any(part.startswith(".") for part in path.relative_to(directory).parts)),
        key=lambda path: str(path).lower(),
    )


def first_with_suffix(files: list[Path], suffixes: set[str]) -> Path | None:
    return next((path for path in files if path.suffix.lower() in suffixes), None)


def discover_item_assets(item_dir: Path) -> dict:
    preview_dir = item_dir / "preview"
    source_dir = item_dir / "source"
    preview_files = list_files(preview_dir)
    source_files = list_files(source_dir)
    entry = preview_dir / "index.html"
    return {
        "preview_files": preview_files,
        "source_files": source_files,
        "interactive_entry": entry if entry.is_file() else None,
        "document": first_with_suffix(preview_files, DOCUMENT_SUFFIXES),
        "image": first_with_suffix(preview_files, IMAGE_SUFFIXES),
        "video": first_with_suffix(preview_files, VIDEO_SUFFIXES),
        "code": first_with_suffix(preview_files, CODE_SUFFIXES),
        "text": first_with_suffix(preview_files, TEXT_SUFFIXES),
    }


def action_link(label: str, href: str, *, download: bool = False, primary: bool = False) -> str:
    attrs = ' class="button-link{}" href="{}"'.format(" button-link-primary" if primary else "", html.escape(href, quote=True))
    if download:
        attrs += " download"
    else:
        attrs += ' target="_blank" rel="noopener"'
    return f"<a{attrs}>{html.escape(label)}</a>"


def render_preview(item: dict, item_dir: Path, assets: dict) -> tuple[str, str | None]:
    preview_type = clean(item.get("preview_type"))
    interactive_entry = assets["interactive_entry"]
    preview_files = assets["preview_files"]

    if preview_type == "interactive" and interactive_entry:
        return ('<div class="preview-frame"><iframe src="preview/" title="Interactive preview" loading="lazy"></iframe></div>', "preview/")

    if preview_type == "document" and assets["document"]:
        path = assets["document"]
        href = web_path(path, item_dir)
        if path.suffix.lower() == ".pdf":
            return (f'<div class="preview-frame preview-document"><iframe src="{html.escape(href, quote=True)}" title="Document preview" loading="lazy"></iframe></div>', href)
        return ('<div class="preview-placeholder"><p>This document format is best opened directly.</p></div>', href)

    if preview_type == "image" and assets["image"]:
        href = web_path(assets["image"], item_dir)
        return (f'<figure class="media-preview"><img src="{html.escape(href, quote=True)}" alt="Preview of {html.escape(clean(item.get("title")))}"></figure>', href)

    if preview_type == "video" and assets["video"]:
        href = web_path(assets["video"], item_dir)
        return (f'<div class="video-preview"><video controls preload="metadata" src="{html.escape(href, quote=True)}">Your browser does not support embedded video.</video></div>', href)

    if preview_type in {"code", "text"}:
        path = assets["code"] if preview_type == "code" else assets["text"]
        if path:
            try:
                content = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                return ('<div class="preview-placeholder"><p>This file cannot be displayed as text in the browser.</p></div>', web_path(path, item_dir))
            truncated = len(content) > 40000
            content = content[:40000]
            note = '<p class="preview-note">Preview truncated after 40,000 characters.</p>' if truncated else ""
            return (f'<div class="text-preview"><div class="preview-file-label">{html.escape(path.name)}</div><pre><code>{html.escape(content)}</code></pre>{note}</div>', web_path(path, item_dir))

    if preview_type == "other" and interactive_entry:
        return ('<div class="preview-frame"><iframe src="preview/" title="Item preview" loading="lazy"></iframe></div>', "preview/")

    if preview_files:
        path = preview_files[0]
        return ('<div class="preview-placeholder"><p>A browser preview is not available for this format, but the preview file can still be opened directly.</p></div>', web_path(path, item_dir))

    message = "This item does not include a browser preview."
    if preview_type == "download":
        message = "This item is provided as a reusable download rather than an in-browser preview."
    elif preview_type == "none":
        message = "This item is informational and does not require a preview."
    return (f'<div class="preview-placeholder"><p>{html.escape(message)}</p></div>', None)


def render_source_files(item_dir: Path, source_files: list[Path]) -> str:
    if not source_files:
        return ""
    rows = []
    for path in source_files:
        href = web_path(path, item_dir)
        name = html.escape(str(path.relative_to(item_dir / "source")))
        rows.append(f'<li><span>{name}</span>{action_link("Download", href, download=True)}</li>')
    return '<section class="item-section"><div class="section-kicker">Reusable files</div><h2>Source downloads</h2><ul class="file-list">{}</ul></section>'.format("".join(rows))


def render_item_page(item: dict, item_dir: Path) -> str:
    assets = discover_item_assets(item_dir)
    preview_markup, preview_href = render_preview(item, item_dir, assets)
    source_files = assets["source_files"]

    content_type = clean(item.get("content_type"))
    if content_type == "Other" and clean(item.get("other_label")):
        content_type = clean(item.get("other_label"))

    status = humanize(clean(item.get("library_status")))
    tools = " · ".join(clean(value) for value in item.get("tools", []) if clean(value))
    tags = "".join(f'<span class="tag-chip">{html.escape(clean(tag))}</span>' for tag in item.get("tags", []) if clean(tag))
    portfolio = clean(item.get("portfolio_status"))

    actions = []
    if preview_href:
        label = "Launch preview" if assets["interactive_entry"] and preview_href == "preview/" else "Open preview"
        actions.append(action_link(label, preview_href, primary=True))
    if len(source_files) == 1:
        actions.append(action_link("Download source", web_path(source_files[0], item_dir), download=True))
    elif len(source_files) > 1:
        actions.append('<a class="button-link" href="#source-downloads">Source files</a>')
    action_markup = f'<div class="item-actions">{"".join(actions)}</div>' if actions else ""

    usage_notes = clean(item.get("usage_notes"))
    usage_markup = ""
    if usage_notes:
        usage_markup = '<section class="item-section"><div class="section-kicker">How to use it</div><h2>Usage notes</h2><p class="item-copy">{}</p></section>'.format(html.escape(usage_notes).replace("\n", "<br>"))

    thumbnail_markup = ""
    thumbnail = clean(item.get("thumbnail"))
    if thumbnail:
        thumb_path = item_dir / thumbnail
        if thumb_path.is_file():
            thumbnail_markup = f'<img class="item-thumbnail" src="{html.escape(web_path(thumb_path, item_dir), quote=True)}" alt="Preview image for {html.escape(clean(item.get("title")))}">'

    source_markup = render_source_files(item_dir, source_files)
    if source_markup:
        source_markup = source_markup.replace('<section class="item-section">', '<section id="source-downloads" class="item-section">', 1)

    updated = clean(item.get("updated"))
    date_line = f'Updated {html.escape(updated)}' if updated else f'Added {html.escape(clean(item.get("created")))}'
    portfolio_line = ""
    if portfolio and portfolio != "library-only":
        portfolio_line = f'<div><dt>Portfolio</dt><dd>{html.escape(humanize(portfolio))}</dd></div>'

    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{html.escape(clean(item.get('summary')), quote=True)}">
  <meta name="theme-color" content="#f8f8f6">
  <title>{html.escape(clean(item.get('title')))} | Learning Content Lab</title>
  <link rel="stylesheet" href="../../css/styles.css">
  <link rel="stylesheet" href="../../css/item-pages.css">
</head>
<body class="item-page">
  <!-- {GENERATED_MARKER} -->
  <header class="site-header">
    <div class="page-shell header-inner">
      <a class="brand" href="../../" aria-label="Learning Content Lab home"><span class="brand-mark" aria-hidden="true">L</span><span>Learning Content Lab</span></a>
      <a class="header-back" href="../../">← Back to library</a>
    </div>
  </header>

  <main>
    <section class="item-hero">
      <div class="page-shell item-hero-grid">
        <div>
          <div class="item-topline"><span class="card-type">{html.escape(content_type)}</span><span class="status-badge" data-status="{html.escape(clean(item.get('library_status')), quote=True)}">{html.escape(status)}</span></div>
          <h1 class="item-title">{html.escape(clean(item.get('title')))}</h1>
          <p class="item-summary">{html.escape(clean(item.get('summary')))}</p>
          {action_markup}
        </div>
        <dl class="item-facts">
          <div><dt>Format</dt><dd>{html.escape(clean(item.get('format')))}</dd></div>
          <div><dt>Tools</dt><dd>{html.escape(tools)}</dd></div>
          <div><dt>Preview</dt><dd>{html.escape(humanize(clean(item.get('preview_type'))))}</dd></div>
          <div><dt>Library</dt><dd>{html.escape(date_line)}</dd></div>
          {portfolio_line}
        </dl>
      </div>
    </section>

    <section class="item-content">
      <div class="page-shell item-content-grid">
        <div>
          {thumbnail_markup}
          <section class="item-section preview-section">
            <div class="section-kicker">Preview</div>
            <h2>See it in action</h2>
            {preview_markup}
          </section>
          {usage_markup}
          {source_markup}
        </div>
        <aside class="item-sidebar">
          <div class="sidebar-card">
            <div class="section-kicker">Tags</div>
            <div class="tag-list">{tags or '<span class="muted-copy">No tags listed.</span>'}</div>
          </div>
          <div class="sidebar-card">
            <div class="section-kicker">Permanent URL</div>
            <p class="muted-copy">This item keeps the same <code>/items/{html.escape(clean(item.get('slug')))}/</code> address when its content is updated.</p>
          </div>
        </aside>
      </div>
    </section>
  </main>

  <footer class="site-footer"><div class="page-shell footer-inner"><p>Learning Content Lab</p><p>Reusable work, experiments, and building blocks.</p></div></footer>
</body>
</html>
'''


def collect_items() -> list[tuple[dict, Path]]:
    items: list[tuple[dict, Path]] = []
    if not ITEMS_DIR.exists():
        return items
    for item_dir in sorted((path for path in ITEMS_DIR.iterdir() if path.is_dir() and not path.name.startswith(".")), key=lambda path: path.name):
        metadata_path = item_dir / "item.json"
        if not metadata_path.is_file():
            continue
        item = load_json(metadata_path)
        if not isinstance(item, dict):
            fail(f"{metadata_path.relative_to(ROOT)} must contain a JSON object")
        slug = clean(item.get("slug"))
        if slug != item_dir.name:
            fail(f"{metadata_path.relative_to(ROOT)} slug must match its folder name")
        items.append((item, item_dir))
    return items


def expected_aggregate(items: list[tuple[dict, Path]]) -> str:
    return json.dumps([item for item, _ in items], indent=2, ensure_ascii=False) + "\n"


def check_or_write(path: Path, expected: str, check: bool) -> None:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == expected:
        return
    if check:
        fail(f"Generated output is stale or missing: {path.relative_to(ROOT)}. Run python scripts/build-library.py")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"WROTE: {path.relative_to(ROOT)}")


def build(check: bool = False) -> int:
    items = collect_items()
    check_or_write(AGGREGATE_PATH, expected_aggregate(items), check)
    for item, item_dir in items:
        check_or_write(item_dir / "index.html", render_item_page(item, item_dir), check)
    mode = "CHECK" if check else "BUILD"
    print(f"{mode}: {len(items)} library item page(s) are in sync")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Learning Content Lab aggregate data and permanent item pages.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are missing or stale instead of writing them.")
    args = parser.parse_args()
    return build(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
