from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def require_tokens(path: Path, tokens: list[str], label: str) -> None:
    content = path.read_text(encoding="utf-8")
    missing = [token for token in tokens if token not in content]
    if missing:
        fail(f"{label} is missing: {', '.join(missing)}")


def main() -> int:
    require_tokens(
        ROOT / "index.html",
        ["css/item-pages.css"],
        "Public homepage Phase 4 contract",
    )
    require_tokens(
        ROOT / "js" / "library.js",
        ["items/${item.slug}/", "View item", "card-action-link"],
        "Library card permanent-link contract",
    )
    require_tokens(
        ROOT / "css" / "item-pages.css",
        [".card-action-link", ".item-hero-grid", ".preview-frame", ".text-preview", ".file-list", "@media (max-width: 680px)"],
        "Item page stylesheet contract",
    )
    require_tokens(
        ROOT / "scripts" / "build-library.py",
        [
            "story.html",
            "render_item_page",
            "preview_type",
            "Source downloads",
            "Generated by scripts/build-library.py",
            "../../css/item-pages.css",
            "../../assets/site/favicon.svg",
            "data-public-guide-open",
            "../../js/public-guide.js",
        ],
        "Item page generator contract",
    )

    print("PASS: Phase 4 permanent links, item page styles, public guide, favicon, and generator contracts are intact")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
